Nebula DEFINITIONS EXPLICIT TAGS ::= BEGIN

Signature ::= OCTET STRING (SIZE (32))
Uint64 ::= INTEGER (0..18446744073709551615)

IPV4 ::= OCTET STRING (SIZE (4))
IPV6 ::= OCTET STRING (SIZE (16))

Certificate ::= SEQUENCE {
	details CertificateDetails,
	signature Signature
}

CertificateDetails ::= SEQUENCE {
	name UTF8String (SIZE (1..253)),

	ip [0] IPNet,
	subnets [1] SEQUENCE SIZE(0..1024) OF IPNet OPTIONAL,
	groups [2] SEQUENCE SIZE(0..1024) OF UTF8String (SIZE(0..1024)) OPTIONAL,

	-- ASN.1 time formats are all string representations
	notBefore Uint64,
	notAfter Uint64,

	publicKey OCTET STRING (SIZE (32)),
	issuer OCTET STRING (SIZE (32)),
	...
}

IPNet ::= CHOICE {
	v4 [0] IPNetV4,
	v6 [1] IPNetV6
}

IPNetV4 ::= SEQUENCE {
	address IPV4,
	suffix INTEGER (0..32)
}

IPNetV6 ::= SEQUENCE {
	address IPV6,
	suffix INTEGER (0..128)
}

END
